version: "3.8"
services:
  web:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
  db:
    image: mariadb:5.5.56
    container_name: mysql-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - ./data-mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8081:80'